name: AutoBuild .NET

on: 
  [push, pull_request]:
    paths:
      - 'TONEX_CHAN/**'
      - 'TestTONEX_CHAN/**'

jobs:
  BuildLiunx:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build TONEX_CHAN/TONEX_CHAN.csproj --configuration Release --output ./TONEX_CHAN/Release
        
      - name: Del
        run: rm -rf ./TONEX_CHAN/Release//TONEX_CHAN.pdb ./TONEX_CHAN/Release//TONEX_CHAN.deps.json ./TONEX_CHAN/Release//TONEX_CHAN.runtimeconfig.json ./TONEX_CHAN/Release//global.json

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TONEX_CHAN-Linux
          path: ./TONEX_CHAN/Release/
          
  BuildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build TONEX_CHAN/TONEX_CHAN.csproj --configuration Release --output ./TONEX_CHAN/Release
        
      - name: Del pdb
        run: del ./TONEX_CHAN/Release/TONEX_CHAN.pdb
      
      - name: Del deps
        run: del ./TONEX_CHAN/Release/TONEX_CHAN.deps.json
        
      - name: Del runtimeconfig
        run: del ./TONEX_CHAN/Release/TONEX_CHAN.runtimeconfig.json
      
      - name: Del global
        run: del ./TONEX_CHAN/Release/global.json
        
      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TONEX_CHAN-Windows
          path: ./TONEX_CHAN/Release/
      
      - name: BuildTestTONEX_CHAN
        run: dotnet build TestTONEX_CHAN/TestTONEX_CHAN.csproj --configuration Release --output TestTONEX_CHAN/Release
        
      - name: Del pdb
        run: del ./TestTONEX_CHAN/Release/TONEX_CHAN.pdb

      - name: Del deps
        run: del ./TestTONEX_CHAN/Release/TONEX_CHAN.deps.json

      - name: Del runtimeconfig
        run: del ./TestTONEX_CHAN/Release/TONEX_CHAN.runtimeconfig.json

      - name: Upload TestTONEX_CHAN
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TestTONEX_CHAN
          path: ./TestTONEX_CHAN/Release