name: AutoBuild .NET

on:
  push:
    paths:
      - 'TONEX_CHAN/**'
      - 'TestTONEX_CHAN/**'
  pull_request:
    paths:
      - 'TONEX_CHAN/**'
      - 'TestTONEX_CHAN/**'

jobs:
  BuildLiunx:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build TONEX_CHAN/TONEX_CHAN.csproj --configuration Release --output ./TONEX_CHAN/Release
        
      - name: Del
        run: rm -rf ./TONEX_CHAN/Release/TONEX_CHAN.pdb ./TONEX_CHAN/Release/TONEX_CHAN.deps.json ./TONEX_CHAN/Release/TONEX_CHAN.runtimeconfig.json ./TONEX_CHAN/Release/global.json

      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TONEX_CHAN-Linux
          path: ./TONEX_CHAN/Release/
          
  BuildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build TONEX_CHAN/TONEX_CHAN.csproj --configuration Release --output C:\TONEX_CHAN\Release
        
      - name: Del pdb
        run: del C:\TONEX_CHAN\Release\TONEX_CHAN.pdb
      
      - name: Del deps
        run: del C:\TONEX_CHAN\Release\TONEX_CHAN.deps.json
        
      - name: Del runtimeconfig
        run: del C:\TONEX_CHAN\Release\TONEX_CHAN.runtimeconfig.json
      
      - name: Del global
        run: del C:\TONEX_CHAN\Release\global.json
        
      - name: Upload
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TONEX_CHAN-Windows
          path: C:\TONEX_CHAN\Release\
      
      - name: Build TestTONEX_CHAN
        run: dotnet build TestTONEX_CHAN/TestTONEX_CHAN.csproj --configuration Release --output C:\TestTONEX_CHAN\Release
        
      - name: Del pdb
        run: del C:\TestTONEX_CHAN\Release\TONEX_CHAN.pdb

      - name: Del deps
        run: del C:\TestTONEX_CHAN\Release\TONEX_CHAN.deps.json

      - name: Del runtimeconfig
        run: del C:\TestTONEX_CHAN\Release\TONEX_CHAN.runtimeconfig.json

      - name: Upload TestTONEX_CHAN
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TestTONEX_CHAN
          path: C:\TestTONEX_CHAN\Release\